# -*- coding: utf-8 -*-
"""final_project (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qrgl-fUaQRLlm2jL5hlVRoG67hLZ2BMG
"""

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np
import seaborn as sns
from google.colab import files

uploaded = files.upload()

upload = files.upload()

df_25 = pd.read_csv('analytic_data2025_v3.csv', low_memory=False, skiprows=1)

df_25.shape

relevant_columns = {
    'fipscode':'fipscode',
    'state': 'state',
    'county': 'county',
    'v147_rawvalue': 'life_expectancy',
    'v063_rawvalue': 'median_household_income',
    'v044_rawvalue': 'income_inequality',
    'v024_rawvalue': 'child_poverty',
    'v023_rawvalue': 'unemployment',
    'v009_rawvalue': 'smoking',
    'v011_rawvalue': 'obesity',
    'v070_rawvalue': 'physical_inactivity',
    'v049_rawvalue': 'excessive_drinking',
    'v143_rawvalue': 'insufficient_sleep',
    'v085_rawvalue': 'uninsured',
    'v004_rawvalue': 'primary_care_physicians',
    'v005_rawvalue': 'preventable_hospital_stays',
    'v062_rawvalue': 'mental_health_providers',
    'v069_rawvalue': 'some_college',
    'v139_rawvalue': 'food_insecurity',
    'v125_rawvalue': 'air_pollution',
    'v136_rawvalue': 'severe_housing_problems',
    'v132_rawvalue': 'exercise_access',
    'v058_rawvalue': 'percent_rural',
    'v053_rawvalue': 'percent_senior',
    'v054_rawvalue': 'percent_black',
    'v056_rawvalue': 'percent_hispanic',
    'v060_rawvalue': 'diabetes_prevalence',
    'v138_rawvalue': 'drug_overdose_deaths',
    'v183_rawvalue': 'loneliness',
    'v083_rawvalue': 'limited_access_healthy_foods',
    'v179_rawvalue': 'access_to_parks',
    'v184_rawvalue': 'lack_social_emotional_support',
    'v155_rawvalue': 'flu_vaccinations',
    'v004_other_data_1': 'ratio_pop_to_pcp',
    'v062_other_data_1': 'ratio_pop_to_mental_health_providers',
    'v124_rawvalue': 'drinking_water_violations'
}

df = df_25[list(relevant_columns.keys())].rename(columns=relevant_columns)

df.info()

sns.histplot(data=df, x='life_expectancy')
plt.title('Distribution of life_expectancy')
plt.xlabel('life_expectancy')
plt.show()

print('median    ', df['life_expectancy'].median())
print(df['life_expectancy'].describe())

states = pd.read_csv('states.csv')
states.rename(columns={'State Code': 'state'}, inplace=True)

df = pd.merge(df, states[['state', 'Region']], on='state', how ='left')

df = df.drop(0)
df.head()

fig, ax = plt.subplots(figsize=(6, 6))
sns.boxplot(data=df, y='life_expectancy', x='Region')
plt.title('life_expectancy distribution by Region')
plt.show()

sns.scatterplot(data=df, x='median_household_income', y='life_expectancy')
plt.title('Income vs Life Expectancy')
plt.xlabel('Median Household Income')
plt.ylabel('Life Expectancy')
plt.show()

# introducing bins for income group and county population density
df['income_group'] = pd.qcut(df['median_household_income'], q=3, labels=['low', 'middle', 'high'])
df['pop_density'] = pd.cut(df['percent_rural'], bins=[0, .33, .66, 1.0], labels=['urban', 'suburban', 'rural'])

#feature creation
df['behavioral_risk_score'] = (df['smoking']+df['obesity']+df['physical_inactivity']+df['excessive_drinking']+df['insufficient_sleep'])/5
df["healthcare_access_score"] = (df['preventable_hospital_stays'] + df['ratio_pop_to_pcp'] + df['uninsured'])/3

# Addressed nulls


num = list(df.select_dtypes(include=['number']).columns)
num.remove("fipscode")

df = df.dropna(subset=['life_expectancy'])
df[num] = df[num].fillna(df.groupby('state')[num].transform('median'))
df[num] = df[num].fillna(df[num].median())

df['ratio_pop_to_pcp'] = df['ratio_pop_to_pcp'].fillna(df['ratio_pop_to_pcp'].median())

correlations = df[num].corrwith(df['life_expectancy'])
correlations.drop('life_expectancy', inplace=True)
plt.figure(figsize=(12, 5))
correlations.sort_values(ascending=False).plot(kind = 'bar')
plt.ylabel("Correlations")
plt.title("Correlation of Features with Life Expectancy")

high_corr_features = ['median_household_income', 'some_college', 'excessive_drinking', 'child_poverty',
                     'food_insecurity', 'smoking', 'physical_inactivity', 'diabetes_prevalence',
                     'insufficient_sleep', 'obesity', 'behavioral_risk_score']

corrmat = df[high_corr_features].corr(method = 'spearman')
corrmat
f, ax = plt.subplots(figsize = (7,7))
sns.heatmap(corrmat, vmax = .8, square = True, annot = True, cmap = 'RdYlBu', linewidths = .5 )
plt.show()

for col in high_corr_features:
    plt.figure(figsize=(5, 6))
    sns.scatterplot(data=df, x=col, y='life_expectancy')
    plt.title(f'{col} vs life_expectancy')
    plt.tight_layout()
    plt.show()

df.groupby('income_group')['life_expectancy'].median().plot(kind='bar')
plt.title('Life Expectancy by Income Group')
plt.xlabel('Income Group')
plt.ylabel('Median Life Expectancy')
plt.show()

df.groupby('pop_density')['life_expectancy'].median()

df[["life_expectancy", "county", "state"]].sort_values(by="life_expectancy")

# Fixed skew
skew = df[num].skew()
skew_to_fix = list(skew[skew >1].index)
df[skew_to_fix] = np.log1p(df[skew_to_fix])

df.info()

# Split data in X and y
y = df['life_expectancy']
X = df.drop(columns=['life_expectancy', 'fipscode', 'county', 'state', 'Region'])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression

median_household_income_X = df[['median_household_income']]
life_expectancy_y = df['life_expectancy']

lin_reg = LinearRegression()
lin_reg.fit(median_household_income_X, life_expectancy_y)

df['life_expectancy_residual'] = life_expectancy_y - lin_reg.predict(median_household_income_X)

df[["county", "state", "life_expectancy_residual", "percent_rural"]].sort_values(by="life_expectancy_residual")

df = df.drop(columns=['life_expectancy_residual'])

cat_attribs = ["income_group", "pop_density"]
num_attribs = list(X.select_dtypes(include=['number']).columns)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA

num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('std_scaler', StandardScaler())
    ])

num_pipeline_pca = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('std_scaler', StandardScaler()),
        ('pca', PCA(n_components=0.95))
    ])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ("encoder", OneHotEncoder(handle_unknown = 'ignore', sparse_output = False))
])

from sklearn.compose import ColumnTransformer

pca_pipeline = Pipeline([
        ("column_transformer", ColumnTransformer([
            ("num", num_pipeline_pca, num_attribs),
            ("cat", cat_pipeline, cat_attribs)
        ]))
    ])

X_train_reduced = pca_pipeline.fit_transform(X_train)
X_test_reduced = pca_pipeline.transform(X_test)

# I used https://www.scikit-yb.org/en/latest/api/cluster/silhouette.html as a source for this code
from sklearn.cluster import KMeans

from yellowbrick.cluster import SilhouetteVisualizer

model_1 = KMeans(5, random_state=42)
visualizer = SilhouetteVisualizer(model_1, colors='yellowbrick')
visualizer.fit(X_train_reduced)
visualizer.show()

model_2 = KMeans(4, random_state=42)
visualizer = SilhouetteVisualizer(model_2, colors='yellowbrick')
visualizer.fit(X_train_reduced)
visualizer.show()

model_3 = KMeans(3, random_state=42)
visualizer = SilhouetteVisualizer(model_3, colors='yellowbrick')
visualizer.fit(X_train_reduced)
visualizer.show()

kmeans = KMeans(n_clusters=4, random_state=42, n_init = 10).fit(X_train_reduced)
df.loc[X_train.index, 'cluster'] = kmeans.labels_
df.loc[X_test.index, 'cluster'] = kmeans.predict(X_test_reduced)

df['fipscode'] = df["fipscode"].astype(str)
df['fipscode'] = df['fipscode'].str.zfill(5)

df.to_csv('tableau_viz_data_sheet_01.csv', index=False)
files.download('tableau_viz_data_sheet_01.csv')

sns.boxplot(data=df, x="cluster", y="life_expectancy")
plt.show();

# I used https://www.geeksforgeeks.org/machine-learning/implementing-pca-in-python-with-scikit-learn/ as a source for this adapted code
plt.scatter(X_train_reduced[:, 0], X_train_reduced[:, 1], c=kmeans.labels_, cmap='Accent', edgecolor='k', s = 10)
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.title("PCA Transformed Clusters")
plt.colorbar(label="Cluster")
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, r2_score

income_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

income_pipeline.fit(X_train[["median_household_income"]], y_train)
y_pred = income_pipeline.predict(X_test[["median_household_income"]])

r2 = r2_score(y_test, y_pred)

scores = cross_val_score(income_pipeline, X_train[["median_household_income"]], y_train, scoring="neg_mean_squared_error", cv=5)
rmse_scores = np.sqrt(-scores)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"R-squared: {r2}")
print(f"RMSE: {rmse}")
print(f"Mean Cross-Validation RMSE: {rmse_scores.mean()}")

lin_reg_pipeline = Pipeline([
        ("column_transformer", ColumnTransformer([
            ("num", num_pipeline, num_attribs),
            ("cat", cat_pipeline, cat_attribs)
        ])),
        ("lin_reg", LinearRegression())
    ])

lin_reg_pipeline.fit(X_train, y_train)
y_pred = lin_reg_pipeline.predict(X_test)

r2 = r2_score(y_test, y_pred)

scores = cross_val_score(lin_reg_pipeline, X_train, y_train, scoring="neg_mean_squared_error", cv=5)
rmse_scores = np.sqrt(-scores)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"R-squared: {r2}")
print(f"RMSE: {rmse}")
print(f"Mean Cross-Validation RMSE: {rmse_scores.mean()}")

lin_reg_pca_pipeline = Pipeline([
    ('model', LinearRegression())
])

lin_reg_pca_pipeline.fit(X_train_reduced, y_train)
y_pred = lin_reg_pca_pipeline.predict(X_test_reduced)

r2 = r2_score(y_test, y_pred)

scores = cross_val_score(lin_reg_pca_pipeline, X_train_reduced, y_train, scoring="neg_mean_squared_error", cv=5)
rmse_scores = np.sqrt(-scores)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"R-squared: {r2}")
print(f"RMSE: {rmse}")
print(f"Mean Cross-Validation RMSE: {rmse_scores.mean()}")

from sklearn.linear_model import Lasso

lasso_pipeline = Pipeline([
    ('column_transformer', ColumnTransformer([
        ('num', num_pipeline, num_attribs),
        ('cat', cat_pipeline, cat_attribs)
    ])),
    ('model', Lasso(max_iter = 10000))
])

param_grid = {
    'model__alpha': [0.0001, 0.001, 0.01, 0.1, 1, 10, 100]
}

grid_search = GridSearchCV(lasso_pipeline, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)
y_pred = grid_search.predict(X_test)

r2 = r2_score(y_test, y_pred)

scores = cross_val_score(grid_search, X_train, y_train, scoring="neg_mean_squared_error", cv=5)
rmse_scores = np.sqrt(-scores)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(grid_search.best_params_)
print(f"R-squared: {r2}")
print(f"RMSE: {rmse}")
print(f"Mean Cross-Validation RMSE: {rmse_scores.mean()}")

from sklearn.ensemble import RandomForestRegressor

random_forest_pipeline = Pipeline([
    ("column_transformer", ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", cat_pipeline, cat_attribs)
    ])),
    ('model', RandomForestRegressor())
])

rf_param_grid = {'model__n_estimators': [100, 200, 300, 400],
                'model__max_features':['sqrt', 'log2'],
                'model__max_depth':[3, 5, 10, 20, None],
                'model__criterion': ['squared_error', 'absolute_error']}

rf_random_search = RandomizedSearchCV(random_forest_pipeline, rf_param_grid,
                         scoring="neg_root_mean_squared_error", cv=5, random_state = 42, n_jobs = -1, n_iter = 10)

rf_random_search.fit(X_train, y_train)
y_pred = rf_random_search.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("Best parameters:",rf_random_search.best_params_)
print(f"R-squared: {r2}")
print(f"RMSE: {rmse}")
print(f"Best CV RMSE: {np.sqrt(-rf_random_search.best_score_)}")

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred, alpha = .5)
plt.axline((56,56), (87,87), color='red', linestyle='--')
plt.xlabel("Actual Life Expectancy")
plt.ylabel("Predicted Life Expectancy")
plt.title('Random Forest Model Performance')
plt.show()

import tensorflow as tf
from tensorflow import keras

mlp_pipeline = Pipeline([
    ("column_transformer", ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", cat_pipeline, cat_attribs)
    ]))])

X_train_mlp = mlp_pipeline.fit_transform(X_train)
X_test_mlp = mlp_pipeline.transform(X_test)

model = keras.models.Sequential([
    keras.layers.Input(shape=(X_train_mlp.shape[1],)),
    keras.layers.Dense(150, activation="relu"),
    keras.layers.Dense(75, activation="relu"),
    keras.layers.Dense(1)
])
model.compile(loss="mean_squared_error", optimizer="adam", metrics = ['mae'])

early_stopping_cb = keras.callbacks.EarlyStopping(patience=5,
                                                  restore_best_weights=True)

history = model.fit(X_train_mlp, y_train, epochs=100, validation_split = .1, callbacks = [early_stopping_cb])
mse_test = model.evaluate(X_test_mlp, y_test)
y_pred = model.predict(X_test_mlp)


rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"R-squared: {r2}")
print(f"RMSE: {rmse}")

